---
# Docker Hub registry secret example
# For other registries (ECR, GCR, etc.), adjust accordingly
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: kpack
  annotations:
    kpack.io/docker: https://index.docker.io/v1/  # Docker Hub registry endpoint
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "******",
          "password": "******",
          "auth": "******"
        }
      }
    }

---
# Example for AWS ECR (uncomment and configure if using ECR)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: registry-credentials
#   namespace: kpack-builds
#   annotations:
#     kpack.io/docker: <account-id>.dkr.ecr.<region>.amazonaws.com
# type: kubernetes.io/dockerconfigjson
# stringData:
#   .dockerconfigjson: |
#     {
#       "auths": {
#         "<account-id>.dkr.ecr.<region>.amazonaws.com": {
#           "username": "AWS",
#           "password": "<ecr-token>"
#         }
#       }
#     }
