---
# Git credentials secret (if using private repository)
# For public repos, this is not needed
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: kpack-builds
  annotations:
    kpack.io/git: https://github.com  # or your git server
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_GIT_USERNAME
  password: YOUR_GIT_TOKEN_OR_PASSWORD

---
# SSH-based git secret example (uncomment if using SSH)
# apiVersion: v1
# kind: Secret
# metadata:
#   name: git-ssh-credentials
#   namespace: kpack-builds
#   annotations:
#     kpack.io/git: git@github.com
# type: kubernetes.io/ssh-auth
# stringData:
#   ssh-privatekey: |
#     -----BEGIN OPENSSH PRIVATE KEY-----
#     <your-private-key-here>
#     -----END OPENSSH PRIVATE KEY-----
